(defun fibsum (max)
  (setq a 1)
  (setq b 1)
  (setq sum 0)
  (while (< (+ a b) 4000000)
    (setq a (+ a b))
    (if (eq 0 (% a 2))
	(setq sum (+ sum a)))
    (setq b (+ b a))
    (if (eq 0 (% b 2))
	(setq sum (+ sum b))))
  (print sum))
(fibsum 40000)
