(defun sm (max)
  (setq i 1)
  (setq sum 0)
  (while (< i max)
    (if (eq 0 (% i 3))
	(setq sum (+ sum i)))
    (if (eq 0 (% i 5))
	(setq sum (+ sum i)))
    (if (and (eq 0 (% i 3)) (= 0 (% i 5)))
	(setq sum (- sum i)))
    (setq i (+ i 1)))
  (print sum))
(sm 1000)
